<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PMUFTWIN101" ignored="0" name="ALL tests in THIS package" tests="9" failures="1" timestamp="24 Oct 2018 11:00:03 GMT" time="0.578" errors="0">
  <testcase name="f" time="0.032" classname="org.rupesh.demo.testng.BasicTestNG1"/>
  <testcase name="a" time="0.014" classname="org.rupesh.demo.testng.BasicTestNG2"/>
  <testcase name="b" time="0.006" classname="org.rupesh.demo.testng.BasicTestNG2">
    <failure type="org.testng.TestException" message="
Expected exception of type class java.lang.ArithmeticException but got java.io.FileNotFoundException">
      <![CDATA[org.testng.TestException: 
Expected exception of type class java.lang.ArithmeticException but got java.io.FileNotFoundException
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException
at org.rupesh.demo.testng.BasicTestNG2.b(BasicTestNG2.java:51)
... 14 more
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- b -->
  <testcase name="c" time="0.006" classname="org.rupesh.demo.testng.BasicTestNG2"/>
  <testcase name="d" time="0.01" classname="org.rupesh.demo.testng.BasicTestNG2"/>
  <testcase name="g" time="0.0" classname="org.rupesh.demo.testng.BasicTestNG2">
    <skipped/>
  </testcase> <!-- g -->
  <testcase name="h" time="0.039" classname="org.rupesh.demo.testng.BasicTestNG2"/>
  <testcase name="e" time="0.0" classname="org.rupesh.demo.testng.BasicTestNG2">
    <skipped/>
  </testcase> <!-- e -->
  <testcase name="f" time="0.01" classname="org.rupesh.demo.testng.BasicTestNG2"/>
</testsuite> <!-- ALL tests in THIS package -->
